### ISSUE TITLE
Deprecation warning when calling `DataFrame()` on a `CompressedSplitDFrameList`

### ISSUE THREAD

**Issue by cvanderaa** [Bioconductor/S4Vectors#91]
Hello, 

I'm experiencing deprecation warnings when calling `DataFrame()` on a `CompressedSplitDFrameList`. See here a reproducible example:

```r
mockDF <- DataFrame(x = runif(9), group = rep(1:3, 3))
mockDFList <- split(mockDF, mockDF$group)
DataFrame(mockDFList)
```

The output is what I expect, but there are 3 deprecation warnings showing up along side...

My session info (R is 4.2.0 and `BiocManager::version()` is 3.15):
```
R Under development (unstable) (2021-11-02 r81131)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] MsCoreUtils_1.7.0           testthat_3.1.0              QFeatures_1.5.1             MultiAssayExperiment_1.21.0 SummarizedExperiment_1.25.1 Biobase_2.55.0             
 [7] GenomicRanges_1.47.3        GenomeInfoDb_1.31.1         IRanges_2.29.0              S4Vectors_0.33.0            BiocGenerics_0.41.1         MatrixGenerics_1.7.0       
[13] matrixStats_0.61.0         

loaded via a namespace (and not attached):
 [1] igraph_1.2.7            rstudioapi_0.13         magrittr_2.0.1          cluster_2.1.2           XVector_0.35.0          zlibbioc_1.41.0         MASS_7.3-54            
 [8] pkgload_1.2.3           clue_0.3-60             lattice_0.20-45         R6_2.5.1                rlang_0.4.12            tools_4.2.0             grid_4.2.0             
[15] cli_3.1.0               withr_2.4.2             ProtGenerics_1.27.0     rprojroot_2.0.2         lazyeval_0.2.2          crayon_1.4.2            Matrix_1.3-4           
[22] GenomeInfoDbData_1.2.7  AnnotationFilter_1.19.0 bitops_1.0-7            RCurl_1.98-1.5          DelayedArray_0.21.1     compiler_4.2.0          desc_1.4.0             
[29] pkgconfig_2.0.3  
```

**Comment by hpages** [comment]
Thanks for the catch.

Should be fixed in release (**S4Vectors** 0.32.1, see commit 17c45ac9a06b51c4f3d0bd41d834f3881123d862), and devel (**S4Vectors** 0.33.1, see commit 8795394eb11df34e348df4e1b6cc232b9ad298a2). **S4Vectors** 0.32.1 should become available via `BiocManager::install()` to BioC 3.14 users in the next 24 hours or so.

Cheers,
H.

**Comment by cvanderaa** [comment]
Thank you @hpages for the fast answer and for the fix! Most of the warnings disappeared in our unit tests, but we still get a warning when the `DFrameList` is a list of `DFrame`s containing a single column. See here the adapted example: 
```r
mockDF <- DataFrame(x = runif(9)) ## the DFrame now has only a single column
group <- rep(1:3, 3)
mockDFList <- split(mockDF, group)
DataFrame(mockDFList)
```
```
DataFrame with 3 rows and 1 column
                              x
                  <NumericList>
1    0.572092,0.474531,0.460234
2 0.6996794,0.0946939,0.8931633
3 0.7030865,0.8816979,0.0540946
```
```
Warning messages:
1: The dim() method for DataFrameList objects is deprecated. Please use dims() on these objects instead. 
2: The nrow() method for DataFrameList objects is deprecated. Please use nrows() on these objects instead. 
3: The ncol() method for CompressedSplitDataFrameList objects is deprecated. Please use ncols() on these objects instead. 
```
Again, the output is as expected except for the deprecation warnings. I'm sorry for this detail remark, I hope I'm not getting too picky here.

**Comment by hpages** [comment]
No you're not. These warnings need to go away for good. Working on it...

**Comment by hpages** [comment]
Should be taken care of in:
- release: **S4Vectors** 0.32.2 (see commit 45e4af94f76edfe96d5f4efe322a0044f0e30d26)
- devel: **S4Vectors** 0.33.2 (see commit dbcf32f40130901d6ef31daf3f462a271095986f)

Hopefully all the `DataFrame(DataFrameList)` warnings are gone now. Please don't hesitate to let me know if they're not.

Note that these new versions won't become available via `BiocManager::install()` before Monday Nov. 8 but you can install directly from GitHub if you need them now (make sure to grab the `RELEASE_3_14` branch if you're using BioC 3.14). Just as a one time exception to the "never install Bioconductor packages directly from GitHub" rule ;-)

Cheers,
H.

**Comment by cvanderaa** [comment]
Excellent, all the warnings are gone on my side as well! Thanks a lot for the rapid fix!
